name: Deploy Application

description: 'Despliega la aplicación en el destino especificado'
inputs:
    deploy-target:
        description: 'Destino de despliegue'
        required: true
        type: string
        default: 'prod-backend1' #Valor por defecto para el input deploy-target

runs:
    using: 'composite'                  #Conjunto de pasos
    steps:
        - name: Deploy to ${{ inputs.deploy-target }}
          run: |
            echo "Desplegando en ${{ inputs.deploy-target }}"
            bash ${{ github.action_path }}/deploy.sh ${{ inputs.deploy-target }} #Referencia de la ruta + Lógica de despliegue (deploy.sh) 
          shell: bash