name: Resuable Frontend CI/CD Workflow

on:
    workflow_call:                                          #Reutilizable. Se puede llamar mediante "uses"
        inputs:
            node-version:                                   #Variable version
                description: 'Versión de Node.js a usar'
                required: true
                type: string
            
            deploy-target:                                  #Variable destino
                description: 'Destino del despliegue (ej. prod-frontend1)'
                required: true
                type: string

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout microHackaton-CleanCode2
              uses: actions/checkout@v3
              with:
                repository: ismaelGTI/microHackaton-CleanCode2
                ref: main
  
            - name: Checkout consumer repo
              uses: actions/checkout@v3
              with:
                path: ./consumer

            - name: Setup Node.js                                                       #Instalar Node.js
              uses: ismaelGTI/microHackaton-CleanCode2/.github/actions/setup-node@main  #Directorio de referencia para el workflow remoto
              with:
                node-version: ${{ inputs.node-version }}
            
            - name: Install dependencies                                           #Instalar dependencias
              run: |
                echo "Instalando dependencias.."
                # npm install
            
            - name: Build                                                          #Compilar el proyecto
              run: |
                echo "Compilando proyecto.."
                # npm run build

            - name: Run Test                                                       #Ejecutar pruebas
              run: |
                echo "Ejecutando pruebas.s."
                # npm test

            - name: Deploy                                                              #Despliegue
              uses: ismaelGTI/microHackaton-CleanCode2/.github/actions/deploy-app@main  #Directorio de referencia para el workflow remoto
              with:
                deploy-target: ${{ inputs.deploy-target }}

            - name: Print env
              run: |
                # Leer variables desde env-template.yml
                DEFAULT_ENV=$(grep "DEFAULT_ENV" templates/env-template.yml | cut -d " " -f 2)
                DEFAULT_REGION=$(grep "DEFAULT_REGION" templates/env-template.yml | cut -d " " -f 2)
                # Exportarlas como variables de entorno
                echo "DEFAULT_ENV=$DEFAULT_ENV" >> $GITHUB_ENV
                echo "DEFAULT_REGION=$DEFAULT_REGION" >> $GITHUB_ENV

                
              
              #Cualquier repo frontend (frontend-app1) llamará a este workflow y pasará sus propios valores para node-version y deploy-target.